### ISSUE TITLE
miTLS2C: Tracking Issue

### ISSUE THREAD

**Issue by jroesch** [mitls/mitls-fstar#186]
We (@nikswamy, @protz, @tahina-pro, @Armael, and I) have begun the process of compiling miTLS to C via Kremlin. This is a tracking issue for the state of the port and the progress we have made so far.

We have begun the process by creating a new [branch](https://github.com/project-everest/everest/tree/c_mitls2c) of `everest` for this process. You can find the related work on each repository in the `c_mitls2c` branch.

The changes on this branch will be mostly contained in Kremlin, and `mitls-fstar`. 

The current working philosophy will be an incremental port. In order to accomplish this we will first generate sub-par code we can test, read, and experiment with. We will iterate towards a final version that generates ideal code.

The current plan for accomplishing this is as follows:

- [x] add a new target to `mitls-fstar` which produces C code for some `.fst`s 
- [x] link this to a C driver which can unit test components
- [x] add Kremlin support for recursive types
- [x] link the generated driver with a conservative GC (libgc)
- [x] rewrite problematics data types and their clients 
- [x] remove types which rely on GC, and rewrite client code
- [x] remove GC 
- [x] ship a GC free C version of mitls

**Comment by jroesch** [comment]
For tomorrow's meeting my goal is to have a set of problematic examples in the current pipeline, and strategies for dealing with them (rewriting code, new types, kremlin support, etc).

**Comment by ad-l** [comment]
Closing, as all the steps above have been done now
